### ISSUE TITLE
Is it possible to give pytorch version in the future?

### ISSUE THREAD

**Issue by MSC19950601** [MrGiovanni/ModelsGenesis#12]
Thanks for your work. Is it possible to give pytorch version in the future?

**Comment by MrGiovanni** [comment]
Certainly. We are working on the PyTorch version and also plan to release the pre-trained weights in PyTorch.
It actually not difficult to translate since our major contribution, a set of image deformations, has been written in a collection of individual python functions, which can be easily adopted in PyTorch. Hopefully, our PyTorch version will be released before Spring Festival, 2020.
Best regards,
Zongwei
