### ISSUE TITLE
Questions about  infinite_generator_3D.py

### ISSUE THREAD

**Issue by lzpwlk123** [MrGiovanni/ModelsGenesis#14]
Hi Zongwei:
Thanks for the excellent job.
I met with some difficulties when trying to learn Models Genesis from my own unlabeled data.
1.  Lines 165 - 181 in  infinite_generator_3D.py,  I guess the intent of the code is to determine whether the crop_window is  lung part.  But I don't understand why it can make it.
2.  For my project,  segmentations of gastrointestinal stromal tumors,  i think i should modify this part ( including the value of config.HU_thred,  config.lung_max and more, i guess),  could you please give me some advise?

Best
lzp

**Comment by MrGiovanni** [comment]
Hi @lzpwlk123 

I agree that infinite_generator_3D.py is a little bit messy because it was implemented for other research purpose before. We are trying to clean it up.

Anyhow, rather than randomly crop sub-volumes from patient CT images, the idea is to crop more informative sub-volumes. We don’t want the cropped sub-volume occupied with 100% of air or fix tissue or background.

For your project, I think you don’t have to follow our complex code to generate sub-volumes. Keep in mind that you want to generate somehow useful sub-volumes for 3D models to learn feature from it. Try to exclude the background in CT/MR images using your talent (do NOT use labels though). 

Best,
Zongwei
