### ISSUE TITLE
Gensis model and pretrained weight of chest 2D 

### ISSUE THREAD

**Issue by luciaL** [MrGiovanni/ModelsGenesis#3]
Hello
The results showed  Models Genesis top any 2D approaches, including ImageNet models. So I‘d like to  try your pretrained weight of 2D.

**Comment by MrGiovanni** [comment]
The results showed **Models Genesis** top any 2D approaches, including ImageNet models.
Our product (Models Genesis) refers to the pre-trained 3D U-Net, so this result demonstrates that pre-trained 3D U-Net (released) top any 2D approaches, including ImageNet models. 

As for 2D weights pre-trained by our self-supervised learning approach, we claim that Models Genesis 2D offer performances _equivalent to_ supervised pre-trained models (ImageNet models). So for 2D model training, we do not recommend you to initialize from our Models Genesis 2D because ImageNet weights are ready-to-use. Models Genesis 2D serve as an ablation study in this work rather than our product.

FYI, we have pre-trained Models Genesis 2D on NIH Chest Xray dataset ([https://nihcc.app.box.com/v/ChestXray-NIHCC](https://nihcc.app.box.com/v/ChestXray-NIHCC)). We may also release these weights in the future if we could further strengthen its transfer learning capability superior to ImageNet weights.

Thanks for your question.
Zongwei

**Comment by argman** [comment]
So in 2D, the pretraining may not be so helpful ?

**Comment by MrGiovanni** [comment]
@argman 
As said, Models Genesis 2D offer performance equivalent to ImageNet models, but still, outperform learning from scratch significantly. This result is unprecedented because our Models Genesis 2D were pre-trained in self-supervision, without using any human annotation, whereas ImageNet demands a huge amount of annotation efforts. But anyhow, our major contribution and focus are to provide pre-trained 3D models for medical imaging. Thanks.
