### ISSUE TITLE
“Tensor” object hs no attribute "assign"

### ISSUE THREAD

**Issue by amberhappy** [MrGiovanni/ModelsGenesis#5]
Thanks so much for sharing the code , and I have some questions. 
1.could you give more information about the version of packages(requirements.txt),I cant reconstruct
the same env with these info.
2. When I using tf=1.14 and keras=2.3.1 . There occurs an error "“Tensor” object hs no attribute "assign""

**Comment by MrGiovanni** [comment]
We have provided 
1. tensorflow-gpu==1.4.0
2. keras==2.1.3
3. tqdm
4. sklearn
5. scikit-image
6. simpleitk

in the current _requirements.txt_
For tensorflow-gpu and keras, we do recommend certain versions because we have noticed that it will possibly go wrong when changing into alternative versions -- for whatever reasons in those versions but not due to our implementation.
I have quickly googled your specific issue, here is a [link](https://github.com/flyyufelix/DenseNet-Keras/issues/1) probably could be helpful for you.
Anyway, if you wish to explore some other versions, you may go through headaches struggling with the env configure issues. I suggest you just simply update them via
```
pip install --upgrade tensorflow-gpu==1.4.0
pip install --upgrade keras==2.1.3
```

As for the other packages in _requirements.txt_, it does not matter which version you choose. Thank you!

Zongwei
