### ISSUE TITLE
About h5 files

### ISSUE THREAD

**Issue by kangyang94** [MrGiovanni/ModelsGenesis#7]
Is there any h5 files which I can download? Or I must pre-train the model by myself.

**Comment by MrGiovanni** [comment]
To download our pre-trained 3D models (formated in .h), please check [here](https://github.com/MrGiovanni/ModelsGenesis#2-download-the-pre-trained-models-genesis) in the ReadMe document. We do not include h5 files in the Github because they are too large. But you can download them via our Google Drive or Baidu Wangpan.
Thanks,
Zongwei
