### ISSUE TITLE
transfer learning in segmentation

### ISSUE THREAD

**Issue by AMSTLHX** [MrGiovanni/ModelsGenesis#9]
The size of the cube   in your pre-trained code is 64X64. But I want to use your pre-trained model to segmentation the nodule , but the DICOM image size is 512X512, what should I do?

**Comment by AMSTLHX** [comment]
If I want to do classification, I am going to migrate directly on the dicom original image or to roughly split the nodule image and then enter the network.

**Comment by JaeZheng** [comment]
> The size of the cube in your pre-trained code is 64X64. But I want to use your pre-trained model to segmentation the nodule , but the DICOM image size is 512X512, what should I do?

Have you fit your problem? I have the same problem as yours, and I try to cut my own 512X512 data to many 64X64 patches and then vote on each pixel when doing segementation prediction on 512X512 image.

**Comment by MrGiovanni** [comment]
> The size of the cube in your pre-trained code is 64X64. But I want to use your pre-trained model to segmentation the nodule, but the DICOM image size is 512X512, what should I do?

@AMSTLHX
@JaeZheng
Directly segmenting nodules from the patient CT scans sized 512x512xZ is a challenging task because nodules usually contain ~100 pixels out of millions of pixels. Therefore, before segmenting nodules, we tend to have a candidate generator (e.g., Fast RCNN) to locate the nodules from patients, crop small cubes (e.g, 64x64x32), and feed into 3D segmentation deep networks.
More details can be found in 

- https://github.com/dhammack/DSB2017/blob/master/dsb_2017_daniel_hammack.pdf
- http://blog.kaggle.com/2017/06/29/2017-data-science-bowl-predicting-lung-cancer-2nd-place-solution-write-up-daniel-hammack-and-julian-de-wit/
- https://eliasvansteenkiste.github.io/machine%20learning/lung-cancer-pred/

**Comment by AMSTLHX** [comment]
How about classification,it also cut into 64X64
x32? And if the nodules is large than 64X64, how to do?

**Comment by MrGiovanni** [comment]
> How about classification, it also cut into 64X64x32?

In our paper, yes, we have cropped input cubes sized 64X64x32 for lung nodule false positive reduction task.
However, our Models Genesis are not limited to this particular input size, thanks to the encoder-decoder architecture and the GlobalAveragePooling3D() layer.

You are free to adopt any arbitrary input size -- keep in mind that input_rows, input_cols, and input_deps should be dividable by 16 (2^4) because there are 4 down-sampling operations.

That said, to segment larger objects, such as liver, kidney, or big nodule :(
you may want to try
`input_channels, input_rows, input_cols, input_deps = 1, 128, 128, 64`
`input_channels, input_rows, input_cols, input_deps = 1, 160, 160, 96`
or even bigger input size as you wish, just depending on how powerful the GPUs you have.
